stages:
  - Build in Release
  - Test
  - Docs

pages:
  stage: Docs
  only:
    - tags
  tags:
    - private-macOS
  script: |
    version=$(git describe --abbrev=0 --tags || echo "0.0.0")
    swift build
    sourcekitten doc --spm-module "RedisNIO" > ./RedisNIO.json
    swift package generate-xcodeproj
    jazzy --clean \
          --author "Nathan Harris (Mordil)" \
          --readme "./README.md" \
          --author_url "https://mordil.info" \
          --github_url "https://gitlab.com/mordil/swift-redis-nio-client" \
          --github-file-prefix https://gitlab.com/mordil/swift-redis-nio-client/blob/$version \
          --root-url "https://mordil.gitlab.io/swift-redis-nio-client/docs/RedisNIO" \
          --module "RedisNIO" \
          --module-version "$version" \
          --theme docs/theme \
          --xcodebuild-arguments -scheme,swift-redis-nio-client-Package \
          --sourcekitten-sourcefile "./RedisNIO.json" \
          --output "./public"
  artifacts:
    paths:
      - public

.build:
  stage: Build in Release
  tags:
    - docker
  script:
    - swift build -c release -v

build 5.0:ubuntu-xenial:
  extends: .build
  image: swift:5.0-xenial
build 5.1:ubuntu-xenial:
  extends: .build
  image: norionomura/swift:swift-5.1-branch
build latest:ubuntu-xenial:
  extends: .build
  image: norionomura/swift:nightly
  allow_failure: true

build 5.0:ubuntu-bionic:
  extends: .build
  image: swift:5.0-bionic

.test:
  stage: Test
  tags:
    - docker
  variables:
    REDIS_URL: 'redis'
    REDIS_PW: 'password'
  services:
  - name: redis:5
    alias: 'redis'
    command: ["redis-server", "--requirepass", "password"]
  script:
    - swift build -v
    - swift test

test 5.0:ubuntu-xenial:
  extends: .test
  image: swift:5.0-xenial
test 5.1:ubuntu-xenial:
  extends: .test
  image: norionomura/swift:swift-5.1-branch
test latest:ubuntu-xenial:
  extends: .test
  image: norionomura/swift:nightly
  allow_failure: true

test 5.0:ubuntu-bionic:
  extends: .test
  image: swift:5.0-bionic
