stages:
  - Platform Tests
  - Docs
 
pages:
  stage: Docs
  only:
    - tags
  image: norionomura/jazzy
  tags:
    - docker
  variables:
    MODULE_NAME: "RediStack"
    REPO_URL: "https://gitlab.com/mordil/swift-redi-stack"
  script: |
    export VERSION=$(git describe --abbrev=0 --tags || echo "0.0.0")
    swift build
    sourcekitten doc --spm-module "$MODULE_NAME" > "./$MODULE_NAME.json"
    jazzy --clean \
          --author "Nathan Harris (Mordil)" \
          --readme "./README.md" \
          --author_url "https://www.mordil.info" \
          --github_url "$REPO_URL" \
          --github-file-prefix "$REPO_URL/blob/$VERSION" \
          --root-url "https://mordil.gitlab.io/swift-redi-stack/" \
          --module "$MODULE_NAME" \
          --module-version "$VERSION" \
          --theme docs/theme \
          --sourcekitten-sourcefile "./$MODULE_NAME.json" \
          --output "./public"
  artifacts:
    paths:
      - public

Ubuntu Bionic:
  stage: Platform Tests
  trigger:
    strategy: depend
    include: '/.gitlab-ci/ubuntu-bionic.yml'

Ubuntu Xenial:
  stage: Platform Tests
  trigger:
    strategy: depend
    include: '/.gitlab-ci/ubuntu-xenial.yml'
