name: Code Coverage

on: [push]

jobs:
  linux-codecov:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/mordil/swift-redi-stack/swift:5.1
    steps:
    - uses: actions/checkout@v1
    - name: Gather code coverage
      run: |
        swift test --enable-code-coverage

        echo "CHILDREN: .build"
        ls .build

        echo "CHILDREN: .build/x86_64-unknown-linux"
        ls .build/x86_64-unknown-linux

        echo "CHILDREN: .build/x86_64-unknown-linux/debug"
        ls .build/x86_64-unknown-linux/debug

        BINARY_PATH=".build/x86_64-unknown-linux/debug/swift-currencyPackageTests.xctest"
        PROF_DATA_PATH=".build/x86_64-unknown-linux/debug/codecov/default.profdata"
        IGNORE_FILENAME_REGEX="(.build|TestUtils|Tests)"

        llvm-cov report \
          $BINARY_PATH \
          --format=text \
          -instr-profile="$PROF_DATA_PATH" \
          -ignore-filename-regex="$IGNORE_FILENAME_REGEX"