name: codecov-linux

on: [push]

jobs:
  codecov-linux:
    runs-on: ubuntu-latest
    image: registry.gitlab.com/mordil/swift-redi-stack/swift:5.1
    steps:
    - uses: actions/checkout@v1
    - name: Codecov
      run: |
        llvm-cov --version
        
        swift test --enable-code-coverage

        BINARY_PATH=".build/x86_64-unknown-linux/debug/redi-stackPackageTests.xctest"
        PROF_DATA_PATH=".build/x86_64-unknown-linux/debug/codecov/default.profdata"
        IGNORE_FILENAME_REGEX="(.build|TestUtils|Tests)"

        echo "Snooping"
        echo "Profdata: " $(ls -l $PROF_DATA_PATH)
        echo "Test binary: " $(ls -l $BINARY_PATH)
        
        llvm-cov report \
          $BINARY_PATH \
          --format=text \
          -instr-profile="$PROF_DATA_PATH" \
          -ignore-filename-regex="$IGNORE_FILENAME_REGEX"
