stages:
  - Test

.unit-test:
  stage: Test
  tags:
    - docker
  variables:
    REDIS_URL: 'redis'
    REDIS_PW: 'password'
    SANITIZER_ARG: '--sanitize=thread'
  services:
  - name: redis:5
    alias: 'redis'
    command: ["redis-server", "--requirepass", "password"]
  script:
    - swift build --build-tests $SANITIZER_ARG -v 
    - swift test --skip-build
